controller_list:
  - name: fake_rh_f0_controller
    type: $(arg fake_execution_type)
    joints:
      - rh_F0_J0
      - rh_F0_J1
      - rh_F0_J2
      - rh_F0_J3
  - name: fake_rh_f1_controller
    type: $(arg fake_execution_type)
    joints:
      - rh_F1_J0
      - rh_F1_J1
      - rh_F1_J2
      - rh_F1_J3
  - name: fake_rh_f2_controller
    type: $(arg fake_execution_type)
    joints:
      - rh_F2_J0
      - rh_F2_J1
      - rh_F2_J2
      - rh_F2_J3
  - name: fake_rh_dx_fingers_controller
    type: $(arg fake_execution_type)
    joints:
      - rh_F0_J0
      - rh_F0_J1
      - rh_F0_J2
      - rh_F0_J3
      - rh_F1_J0
      - rh_F1_J1
      - rh_F1_J2
      - rh_F1_J3
      - rh_F2_J0
      - rh_F2_J1
      - rh_F2_J2
      - rh_F2_J3
  - name: fake_rh_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - rh_F0_J0
      - rh_F0_J1
      - rh_F0_J2
      - rh_F0_J3
      - rh_F1_J0
      - rh_F1_J1
      - rh_F1_J2
      - rh_F1_J3
      - rh_F2_J0
      - rh_F2_J1
      - rh_F2_J2
      - rh_F2_J3
initial:  # Define initial robot poses per group
#  - group: rh_f0
#    pose: home

  []