# Copyright (C) 2024 Shadow Robot Company Ltd - All Rights Reserved. Proprietary and Confidential.
# Unauthorized copying of the content in this file, via any medium is strictly prohibited.

joint_effort_controller:
  command_timeout: 5.0
  type: dx_controllers/FingerPassThroughEffortController
  param_namespace: /dx_finger
  finger_names: [F0, F1, F2]
  fingers:
    F0:
      actuators:
        - F0_A0
        - F0_A1
        - F0_A2
        - F0_A3
        - F0_A4
      joints:
        - rh_F0_J0
        - rh_F0_J1
        - rh_F0_J2
        - rh_F0_J3
        
    F1:
      actuators:
        - F1_A0
        - F1_A1
        - F1_A2
        - F1_A3
        - F1_A4
      joints:
        - rh_F1_J0
        - rh_F1_J1
        - rh_F1_J2
        - rh_F1_J3

    F2:
      actuators:
        - F2_A0
        - F2_A1
        - F2_A2
        - F2_A3
        - F2_A4
      joints:
        - rh_F2_J0
        - rh_F2_J1
        - rh_F2_J2
        - rh_F2_J3
