# Copyright (C) 2024 Shadow Robot Company Ltd - All Rights Reserved. Proprietary and Confidential.
# Unauthorized copying of the content in this file, via any medium is strictly prohibited.

position_controller:
  update_period: 0.001
  command_timeout: 5.0
  type: dx_controllers/FingerPositionController
  param_namespace: /dx_finger
  finger_names: [rh_F0, rh_F1, rh_F2]
  publish_individual_controller_states: true
  
  fingers:
    rh_F0:
      actuators:
        - rh_F0_A0
        - rh_F0_A1
        - rh_F0_A2
        - rh_F0_A3
        - rh_F0_A4
      joints:
        - rh_F0_J0
        - rh_F0_J1
        - rh_F0_J2
        - rh_F0_J3

      rh_F0_J0:
        max_slew_rate: 3.141
        velocity_smoothing_length: 12
        pid:
          publish_state: false
          p: 2.8
          i: 4.0
          d: 0.03
          i_clamp_min: -0.1
          i_clamp_max: 0.1
          antiwindup: true

      rh_F0_J1:
        max_slew_rate: 3.141
        velocity_smoothing_length: 12
        pid:
          publish_state: False
          p: 2.5
          i: 3.0
          d: 0.02  #0.01
          i_clamp_min: -0.2
          i_clamp_max: 0.2
          antiwindup: true

      rh_F0_J2:
        max_slew_rate: 3.141
        velocity_smoothing_length: 12
        pid:
          publish_state: False
          p: 1.1
          i: 3.0
          d: 0.01
          i_clamp_min: -0.2
          i_clamp_max: 0.2
          antiwindup: true

      rh_F0_J3:
        max_slew_rate: 3.141
        velocity_smoothing_length: 12
        pid:
          publish_state: False
          p: 0.6
          i: 3.0
          d: 0.008
          i_clamp_min: -0.1
          i_clamp_max: -0.1
          antiwindup: true
    rh_F1:
      actuators:
        - rh_F1_A0
        - rh_F1_A1
        - rh_F1_A2
        - rh_F1_A3
        - rh_F1_A4
      joints:
        - rh_F1_J0
        - rh_F1_J1
        - rh_F1_J2
        - rh_F1_J3

      rh_F1_J0:
        max_slew_rate: 3.141
        velocity_smoothing_length: 12
        pid:
          publish_state: false
          p: 2.8
          i: 4.0
          d: 0.03
          i_clamp_min: -0.1
          i_clamp_max: 0.1
          antiwindup: true

      rh_F1_J1:
        max_slew_rate: 3.141
        velocity_smoothing_length: 12
        pid:
          publish_state: False
          p: 2.5
          i: 3.0
          d: 0.02  #0.01
          i_clamp_min: -0.2
          i_clamp_max: 0.2
          antiwindup: true

      rh_F1_J2:
        max_slew_rate: 3.141
        velocity_smoothing_length: 12
        pid:
          publish_state: False
          p: 1.1
          i: 3.0
          d: 0.01
          i_clamp_min: -0.2
          i_clamp_max: 0.2
          antiwindup: true

      rh_F1_J3:
        max_slew_rate: 3.141
        velocity_smoothing_length: 12
        pid:
          publish_state: False
          p: 0.6
          i: 3.0
          d: 0.008
          i_clamp_min: -0.1
          i_clamp_max: -0.1
          antiwindup: true
    rh_F2:
      actuators:
        - rh_F2_A0
        - rh_F2_A1
        - rh_F2_A2
        - rh_F2_A3
        - rh_F2_A4
      joints:
        - rh_F2_J0
        - rh_F2_J1
        - rh_F2_J2
        - rh_F2_J3

      rh_F2_J0:
        max_slew_rate: 3.141
        velocity_smoothing_length: 12
        pid:
          publish_state: false
          p: 2.8
          i: 4.0
          d: 0.03
          i_clamp_min: -0.1
          i_clamp_max: 0.1
          antiwindup: true

      rh_F2_J1:
        max_slew_rate: 3.141
        velocity_smoothing_length: 12
        pid:
          publish_state: False
          p: 2.5
          i: 3.0
          d: 0.02  #0.01
          i_clamp_min: -0.2
          i_clamp_max: 0.2
          antiwindup: true

      rh_F2_J2:
        max_slew_rate: 3.141
        velocity_smoothing_length: 12
        pid:
          publish_state: False
          p: 1.1
          i: 3.0
          d: 0.01
          i_clamp_min: -0.2
          i_clamp_max: 0.2
          antiwindup: true

      rh_F2_J3:
        max_slew_rate: 3.141
        velocity_smoothing_length: 12
        pid:
          publish_state: False
          p: 0.6
          i: 3.0
          d: 0.008
          i_clamp_min: -0.1
          i_clamp_max: -0.1
          antiwindup: true
