# Copyright (C) 2024-2025 Shadow Robot Company Ltd - All Rights Reserved. Proprietary and Confidential.
# Unauthorized copying of the content in this file, via any medium is strictly prohibited.

trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  hardware_interface:
    joints: &robot_joints
      - a0_shoulder_pan_joint
      - a0_shoulder_lift_joint
      - a0_elbow_joint
      - a0_wrist_1_joint
      - a0_wrist_2_joint
      - a0_wrist_3_joint
  joints: *robot_joints
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      a0_shoulder_pan_joint: {trajectory: 0.3, goal: 0.1}
      a0_shoulder_lift_joint: {trajectory: 0.3, goal: 0.1}
      a0_elbow_joint: {trajectory: 0.3, goal: 0.1}
      a0_wrist_1_joint: {trajectory: 0.3, goal: 0.1}
      a0_wrist_2_joint: {trajectory: 0.3, goal: 0.1}
      a0_wrist_3_joint: {trajectory: 0.3, goal: 0.1}
  stop_trajectory_duration: 0.5
  allow_partial_joints_goal: true