#!/usr/bin/python3

# Software License Agreement (BSD License)
# Copyright © 2025 belongs to Shadow Robot Company Ltd.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#   1. Redistributions of source code must retain the above copyright notice,
#      this list of conditions and the following disclaimer.
#   2. Redistributions in binary form must reproduce the above copyright notice,
#      this list of conditions and the following disclaimer in the documentation
#      and/or other materials provided with the distribution.
#   3. Neither the name of Shadow Robot Company Ltd nor the names of its contributors
#      may be used to endorse or promote products derived from this software without
#      specific prior written permission.
#
# This software is provided by Shadow Robot Company Ltd "as is" and any express
# or implied warranties, including, but not limited to, the implied warranties of
# merchantability and fitness for a particular purpose are disclaimed. In no event
# shall the copyright holder be liable for any direct, indirect, incidental, special,
# exemplary, or consequential damages (including, but not limited to, procurement of
# substitute goods or services; loss of use, data, or profits; or business interruption)
# however caused and on any theory of liability, whether in contract, strict liability,
# or tort (including negligence or otherwise) arising in any way out of the use of this
# software, even if advised of the possibility of such damage.

import rospy
from rosparam import get_param, upload_params
from sr_utilities_common.wait_for_param import wait_for_param

if __name__ == "__main__":
    rospy.init_node("copy_parameter")

    from_ns = rospy.get_param("~from_ns")
    to_ns = rospy.get_param("~to_ns")
    param_name = rospy.get_param("~param_name")
    seconds_to_wait = rospy.get_param("~seconds_to_wait", 0)

    wait_for_param(from_ns + "/" + param_name, 0)

    if seconds_to_wait > 0:
        rospy.sleep(seconds_to_wait)

    value = get_param(from_ns + "/" + param_name)
    upload_params(to_ns + "/" + param_name, value)
    rospy.loginfo(f"Parameter {param_name} copied from {from_ns} to {to_ns}")